import { isIncludedIn } from 'remeda';

export const rarities = ['4', '5'] as const;
export type Rarity = (typeof rarities)[number];

export const elements = [
	'anemo',
	'cryo',
	'dendro',
	'electro',
	'geo',
	'hydro',
	'pyro',
	'none'
] as const;
export type Element = (typeof elements)[number];

export const isRarity = (value: string): value is Rarity => isIncludedIn(value, rarities);

export const isElement = (value: string): value is Element => isIncludedIn(value, elements);

export interface ElementData {
	id: Element;
	iconUrl: string;
}
/**
 * A playable character, trimmed from `genshin-db` for the web UI.
 *
 * Differs from the CLI trim: keeps `region` and the full-URL portrait/icon
 * fields the UI presents, drops the bare `filename_*` images and stat
 * functions that don't serialize. Generated by `scripts/gen-data.ts`.
 */
export interface Char {
	id: number;
	name: string;
	title: string;
	rarity: 4 | 5;
	/** Lowercased element, matching the `elements` form values (e.g. `pyro`). */
	element: Element;
	elementText: string;
	weaponText: string;
	/** Home region, e.g. `Liyue`. Empty for the Traveler and crossovers (Aloy). */
	region: string;
	/** Tall portrait URL (wikia), or `undefined` when unavailable. */
	portrait: string | undefined;
	/** Square avatar URL (hoyolab), or `undefined` when unavailable. */
	icon: string | undefined;
	/** Fandom wiki link, or `undefined` when unavailable. */
	fandomUrl: string | undefined;
}

/**
 * A boss enemy, trimmed from `genshin-db`. Text-only: `genshin-db` exposes no
 * usable image URL for enemies (only a bare icon filename), so no art is kept.
 */
export interface Enemy {
	name: string;
	description: string;
	categoryType: string;
	enemyType: string;
}
